"""Person's phone number

Revision ID: 508ea46bfff0
Revises: 868c9a86e5d3
Create Date: 2024-05-15 12:24:37.488105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508ea46bfff0'
down_revision: Union[str, None] = '868c9a86e5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'phone_number')
    # ### end Alembic commands ###
