"""People table

Revision ID: 868c9a86e5d3
Revises: 543b22dd681b
Create Date: 2024-05-15 12:11:11.634473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868c9a86e5d3'
down_revision: Union[str, None] = '543b22dd681b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('person_id', sa.Integer(), nullable=True))
    op.drop_constraint('addresses_user_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'people', ['person_id'], ['id'])
    op.drop_column('addresses', 'state')
    op.drop_column('addresses', 'country')
    op.drop_column('addresses', 'user_id')
    op.drop_constraint('parcels_sender_id_fkey', 'parcels', type_='foreignkey')
    op.drop_constraint('parcels_recipient_id_fkey', 'parcels', type_='foreignkey')
    op.create_foreign_key(None, 'parcels', 'people', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'parcels', 'people', ['recipient_id'], ['id'])
    op.add_column('people', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('people', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('people', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=True)
    op.add_column('users', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'people', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'person_id')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.alter_column('people', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('people', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('people', 'email')
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.create_foreign_key('parcels_recipient_id_fkey', 'parcels', 'users', ['recipient_id'], ['id'])
    op.create_foreign_key('parcels_sender_id_fkey', 'parcels', 'users', ['sender_id'], ['id'])
    op.add_column('addresses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key('addresses_user_id_fkey', 'addresses', 'users', ['user_id'], ['id'])
    op.drop_column('addresses', 'person_id')
    # ### end Alembic commands ###
